parameters:
- name: target
  displayName: Target
  type: string
  default: all
  values:
  - All
  - Windows (x64)
  - Windows (x86)
  - Linux (x64)
  - Linux (ARM)
  - Linux (ARM64)
  - RHEL 6 (x64)
  - macOS (x64)

pr:
  branches:
    include:
    - '*'
  paths:
    exclude:
    - 'docs/*'

extends:
  template: .azure-pipelines/pipeline.yml
  parameters:
    componentDetection: ${{ eq(variables['Build.Reason'], 'PullRequest') }}
    publishArtifacts: ${{ ne(variables['Build.Reason'], 'PullRequest') }}
    target: ${{ parameters.target }}
