pr:
  branches:
    include:
    - '*'
  paths:
    exclude:
    - 'docs/*'

extends:
  template: .azure-pipelines/pipeline.yml
  parameters:
    componentDetection: ${{ eq(variables['Build.Reason'], 'PullRequest') }}
    publishArtifacts: ${{ ne(variables['build.reason'], 'PullRequest') }}
