# This Yaml Document has been converted by ESAI Yaml Pipeline Conversion Tool.

trigger: none

parameters:
- name: version
  type: string
  displayName: Version
  default: 'NotSet'
- name: derivedFrom
  type: string
  displayName: Derived From Version
  default: latest
- name: skipTests
  type: boolean
  default: false
  displayName: Skip Tests
# buildStageOnly is useful for testing changes of the build stage which cannot be tested
# in the ci project, like signing, without actually doing a release
- name: buildStageOnly
  type: boolean
  default: false
  displayName: Build Stage Only

- name: onlyGitHubRelease
  type: boolean
  default: false
  displayName: Release only for GitHub

- name: testProxyAgent
  type: boolean
  default: true
  displayName: Test Proxy Agent

- name: disableNotifications
  type: boolean
  default: false
  displayName: Disable Teams Notifications

# Skip CG
variables:
  - name: OneES_JobScannedCount
    value: 1

jobs:
################################################################################
- job: Create_Release_Branch
################################################################################
  displayName: Create Release Branch
  variables:
    AgentVersion: "1.111.999"
  pool:
    name: 1ES-ABTT-Shared-Pool
    image: abtt-ubuntu-2204
    os: linux
  steps:

  - checkout: self

  - task: NodeTool@0
    displayName: Use node 14.15.1
    inputs:
      versionSpec: "14.15.1"

  - bash: |
      set -x
      cd release
      npm install
      ls
      node createAdoPrs.js $(AgentVersion)
    name: s_CreateAdoPrs
    displayName: Create PRs in AzureDevOps and ConfigChange
    env:
      USERNAME: $(User)
      PAT: $(System.AccessToken)
      USEREMAIL: $(Email)