parameters:
  componentDetection: 'false'
  testLogTitle: 'Non-Windows'
  enableADOLogIssue: 'false'

steps:

- ${{ if eq(parameters.componentDetection, 'true') }}:
    # Component detection
    - task: ms.vss-governance-buildtask.governance-build-task-component-detection.ComponentGovernanceComponentDetection@0
      displayName: 'Component Detection'
      condition: and(succeeded(), eq(variables['Build.Reason'], 'PullRequest'))

# Clean
- checkout: self
  clean: true

- ${{ if ne(parameters.version, '') }}:
    - script: git checkout releases/$(version)
      displayName: Checkout release branch

# Build agent layout
- script: ./dev.sh layout Release
  workingDirectory: src
  displayName: Build & Layout Release
  env:
    ADO_ENABLE_LOGISSUE: ${{ parameters.enableADOLogIssue }}

# Run test
- script: ./dev.sh test
  workingDirectory: src
  displayName: Test

# Publish test results
- task: PublishTestResults@2
  displayName: Publish Test Results **/*.trx
  condition: always()
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'
    testRunTitle: 'Agent Tests - ${{ parameters.testLogTitle }}'

# Upload test log
- task: PublishBuildArtifacts@1
  displayName: Publish Test logs
  condition: always()
  inputs:
    pathToPublish: src/Test/TestLogs
    artifactName: ${{ parameters.testLogTitle }}-$(System.JobId)
    artifactType: container
