parameters:
- name: test
  type: boolean
  default: true
- name: publishArtifacts
  type: boolean
  default: false
- name: buildAlternatePackage
  type: boolean
  default: true
- name: branch
  type: string
  default: ''

# Targets
- name: linux_arm
  type: boolean
  default: true

resources:
  containers:
  - container: dotnetcore_arm
    image: azpagentinfra/arm:latest

stages:
- stage: build
  displayName: Build
  jobs:

  # Linux (ARM)
  - ${{ if parameters.linux_arm }}:
    - template: build-jobs.yml
      parameters:
        jobName: build_linux_arm
        displayName: Linux (ARM)
        pool:
        # should be replaced by real raspberry pi pool, once it will be implemented
          vmImage: "ubuntu-20.04"
        # container: dotnetcore_arm
        timeoutInMinutes: 75
        os: linux
        arch: arm
        branch: ${{ parameters.branch }}
        componentDetection: false
        unitTests: false
        functionalTests: false
        sign: false
        publishArtifacts: ${{ parameters.publishArtifacts }}
        buildAlternatePackage: ${{ parameters.buildAlternatePackage }}
