parameters:
- name: layoutRoot
  type: string
- name: isWindows
  type: boolean
  default: true

steps:
- ${{ if parameters.isWindows }}:
  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        $errors = New-Object Collections.Generic.List[String]
        $success = New-Object Collections.Generic.List[String]
        $ErrorActionPreference = 'Stop'
        $windowsSdkPath=Get-ChildItem "${Env:ProgramFiles}\Windows Kits\10\bin\1*" | Select-Object FullName | Sort-Object -Descending { [version](Split-Path $_.FullName -leaf)} | Select-Object -first 1
        Write-Host $windowsSdkPath
        foreach ($tree in Get-ChildItem -Path '${{ parameters.layoutRoot }}/bin' -Filter "*.dll" | select FullName) {
          try {
            # Write-Host $tree.FullName
            & "$($windowsSdkPath.FullName)\x64\signtool" remove /s /q "$($tree.FullName)" 2>&1
            if ($lastexitcode -ne 0) {
              # Write-Warning "Something went wrong, failed to process $tree file in try"
              $errors.Add("$($tree.FullName)")
            } else {
              $error
              $success.Add("$($tree.FullName)")
            }
          } catch {
            $error
            $errors.Add("$($tree.FullName)")
            # Write-Warning "Something went wrong, failed to process $tree file in catch"
          }
        }
        foreach ($e in $errors) {
          # Write-Warning "Something went wrong, failed to process $e file in catch"
        }
        foreach ($s in $success) {
          # Write-Host "Signature succefully removed for $s file"
        }
      ignoreLASTEXITCODE: true

  - task: SFP.build-tasks.custom-build-task-1.EsrpCodeSigning@1
    inputs:
      ConnectedServiceName: VSTSAgentESRP
      FolderPath: '${{ parameters.layoutRoot }}/bin'
      Pattern: AgentService.exe
      signConfigType: inlineSignParams
      inlineOperation: |
        [{
        "keyCode": "CP-235845-SN",
        "operationSetCode": "StrongNameSign",
        "parameters": [],
        "toolName": "sign",
        "toolVersion": "1.0"
        },
        {
        "keyCode": "CP-235845-SN",
        "operationSetCode": "StrongNameVerify",
        "parameters": [],
        "toolName": "sign",
        "toolVersion": "1.0"
        }
        ]
    displayName: Sign Agent Assemblies (Strong Name Signing)

- task: SFP.build-tasks.custom-build-task-1.EsrpCodeSigning@1
  inputs:
    ConnectedServiceName: VSTSAgentESRP
    FolderPath: '${{ parameters.layoutRoot }}/bin'
    Pattern: |
      Agent.*.dll
      Agent.*.exe
      Microsoft.VisualStudio.Services.Agent.dll
      AgentService.exe
      **\AgentService.resources.dll
    UseMinimatch: true
    signConfigType: inlineSignParams
    inlineOperation: |
      [{
      "keyCode": "CP-230012",
      "operationSetCode": "SigntoolSign",
      "parameters": [{
      "parameterName": "OpusName",
      "parameterValue": "Microsoft"
      },
      {
      "parameterName": "OpusInfo",
      "parameterValue": "http://www.microsoft.com"
      },
      {
      "parameterName": "FileDigest",
      "parameterValue": "/fd \"SHA256\""
      },
      {
      "parameterName": "PageHash",
      "parameterValue": "/NPH"
      },
      {
      "parameterName": "TimeStamp",
      "parameterValue": "/tr \"http://rfc3161.gtm.corp.microsoft.com/TSS/HttpTspServer\" /td sha256"
      }
      ],
      "toolName": "sign",
      "toolVersion": "1.0"
      },
      {
      "keyCode": "CP-230012",
      "operationSetCode": "SigntoolVerify",
      "parameters": [],
      "toolName": "sign",
      "toolVersion": "1.0"
      }
      ]
  displayName: Sign Agent Assemblies (Authenticode Signing)

- task: SFP.build-tasks.custom-build-task-1.EsrpCodeSigning@1
  inputs:
    ConnectedServiceName: VSTSAgentESRP
    FolderPath: '${{ parameters.layoutRoot }}'
    Pattern: |
      bin\powershell\**\*.ps1
      bin\powershell\**\*.psm1
      externals\vstshost\**\*.ps1
      externals\vstshost\**\*.psd1
      externals\vstshost\**\*.psm1
    UseMinimatch: true
    signConfigType: inlineSignParams
    inlineOperation: |
      [{
      "keyCode": "CP-230012",
      "operationSetCode": "SigntoolSign",
      "parameters": [{
      "parameterName": "OpusName",
      "parameterValue": "Microsoft"
      },
      {
      "parameterName": "OpusInfo",
      "parameterValue": "http://www.microsoft.com"
      },
      {
      "parameterName": "FileDigest",
      "parameterValue": "/fd \"SHA256\""
      },
      {
      "parameterName": "PageHash",
      "parameterValue": "/NPH"
      },
      {
      "parameterName": "TimeStamp",
      "parameterValue": "/tr \"http://rfc3161.gtm.corp.microsoft.com/TSS/HttpTspServer\" /td sha256"
      }
      ],
      "toolName": "sign",
      "toolVersion": "1.0"
      },
      {
      "keyCode": "CP-230012",
      "operationSetCode": "SigntoolVerify",
      "parameters": [],
      "toolName": "sign",
      "toolVersion": "1.0"
      }
      ]
  displayName: Sign PowerShell Scripts (Authenticode Signing)

- task: SFP.build-tasks.custom-build-task-1.EsrpCodeSigning@1
  inputs:
    ConnectedServiceName: VSTSAgentESRP
    FolderPath: '${{ parameters.layoutRoot }}'
    Pattern: |
      bin\**\*.dll
      externals\git\**\*.dll
      externals\git\**\*.exe
      externals\node\bin\node.exe
      externals\node10\bin\node.exe
      externals\vstshost\Minimatch.dll
      externals\vstsom\Newtonsoft.Json.dll
      externals\tf\Newtonsoft.Json.dll
    UseMinimatch: true
    signConfigType: inlineSignParams
    inlineOperation: |
      [{
      "keyCode": "CP-231522",
      "operationSetCode": "SigntoolSign",
      "parameters": [{
      "parameterName": "OpusName",
      "parameterValue": "Microsoft"
      },
      {
      "parameterName": "OpusInfo",
      "parameterValue": "http://www.microsoft.com"
      },
      {
      "parameterName": "Append",
      "parameterValue": "/as"
      },
      {
      "parameterName": "FileDigest",
      "parameterValue": "/fd \"SHA256\""
      },
      {
      "parameterName": "PageHash",
      "parameterValue": "/NPH"
      },
      {
      "parameterName": "TimeStamp",
      "parameterValue": "/tr \"http://rfc3161.gtm.corp.microsoft.com/TSS/HttpTspServer\" /td sha256"
      }
      ],
      "toolName": "sign",
      "toolVersion": "1.0"
      },
      {
      "keyCode": "CP-231522",
      "operationSetCode": "SigntoolVerify",
      "parameters": [],
      "toolName": "sign",
      "toolVersion": "1.0"
      }
      ]
  displayName: Sign Agent Assemblies (3rd Party Assemblies Signing)

- task: DeleteFiles@1
  inputs:
    SourceFolder: '${{ parameters.layoutRoot }}'
    Contents: '**\CodeSignSummary-*.md'
  displayName: Delete CodeSignSummary.md
